MovieShopMVC/Models/ErrorViewModel.cs
using System;

namespace MovieShopMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MovieShopMVC/Controllers/AccountController.cs
using ApplicationCore.Models;
using Infrastructure.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserService _userService;

        public AccountController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Register(UserRegisterRequestModel model)
        {
            // check if model validation passes
            if (!ModelState.IsValid)
            {
                return View();
            }
            var createdUser = await _userService.RegisterUser(model);
            return RedirectToAction("Login");
        }

        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Login(UserLoginRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            var user = await _userService.Login(model.Email, model.Password);
            if(user == null)
            {
                ModelState.AddModelError(string.Empty, "Invalid password");
                return View(); 
            }

            // create your id card 

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Email, user.Email),
                new Claim(ClaimTypes.GivenName, user.FirstName),
                new Claim(ClaimTypes.Surname, user.LastName),
                new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
            };

            // identity object

            var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

            // create the cookie 
            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));

            return LocalRedirect("~/");
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

MovieShopMVC/Controllers/CastsController.cs
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class CastsController : Controller
    {
        private readonly ICastService _castService;

        public CastsController(ICastService castService)
        {
            _castService = castService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var cast = await _castService.GetCastDetails(id);
            return View(cast);
        }
    }
}

MovieShopMVC/Controllers/GenresController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class GenresController : Controller
    {
        private readonly IGenreService _genreService;

        public GenresController(IGenreService genreService)
        {
            _genreService = genreService;
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var genre = await _genreService.GetGenreDetails(id);
            return View(genre);
        }
    }
}

MovieShopMVC/Controllers/HomeController.cs
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using MovieShopMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class HomeController : Controller
    {
        private IMovieService _movieService;
        public HomeController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task< IActionResult> Index()
        {
            var movies = await _movieService.GetTopRevenueMovies();

            // 3 ways to send the data from Controller/action to View
            // 1. Models (strongly typed models)
            // 2. ViewBag
            // 3. ViewData
            ViewBag.MoviesCount = movies.Count();

            return View(movies);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        // GET localhost:5001/home/GetHighestGrossingMovies
        [HttpGet]
        public IActionResult GetHighestGrossingMovies()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MovieShopMVC/Controllers/MoviesController.cs
using ApplicationCore.ServiceInterfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class MoviesController : Controller
    {
        private readonly IMovieService _movieService;

        public MoviesController(IMovieService movieService)
        {
            _movieService = movieService;
        }

        public async Task<IActionResult> Details(int id)
        {
            var movie = await _movieService.GetMovieDetails(id);
            return View(movie);
        }
    }
}

MovieShopMVC/Controllers/UsersController.cs
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieShopMVC.Controllers
{
    public class UsersController : Controller
    {
        private readonly IUserService _userService;
        private readonly ICurrentUser _currentUser;

        public UsersController(IUserService userService, ICurrentUser currentUser)
        {
            _userService = userService;
            _currentUser = currentUser;
        }
        [HttpPost]
        public async Task<IActionResult> BuyMovie(int id)
        {
            if (!_currentUser.isAuthenticated)
            {
                return RedirectToAction("Login", "Account");
            }
            var movie = await _userService.BuyMovie(id);
            return View("TransactionComplete", movie);
        }
    }
}

MovieShopMVC/Views/Casts/Details.cshtml
@model ApplicationCore.Models.CastDetailsResponseModel

@{
    ViewData["Title"] = "Cast Detail Page";
}


<div class="rounded">
    <div class="container">
        <div class="row p-5">
            <div class="col-2 offset-3">
                <img class="w-75 " src="@Model.ProfilePath" alt="@Model.Name">
            </div>
            <div class="col">
                <h1 class="">@Model.Name</h1>
                <h3>
                    @(Model.Gender == "1" ? "Actress" : (Model.Gender == "2") ? "Actor" : "")
                    <a href="@Model.TmdbUrl" class="text-dark mx-3">
                        <i class="fa fa-share-square-o" aria-hidden="true"></i>
                    </a>
                </h3>
            </div>
        </div>
    </div>

    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in @Model.Movies)
            {
                <div class="col-3">
                    <partial name="_MovieCard" model="movie" />
                    @*@await Html.PartialAsync(partialViewName: "_MovieCard", movie)*@
                </div>
            }
        </div>
    </div>
</div>

MovieShopMVC/Views/Genres/Details.cshtml
@model ApplicationCore.Models.GenreDetailsResponseModel

@{
    ViewData["Title"] = "Genre Detail Page";
}


<div class="rounded">
    <h1 class="text-center">@Model.Name</h1>
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in @Model.Movies)
            {
                <div class="col-3">
                    <partial name="_MovieCard" model="movie" />
                    @*@await Html.PartialAsync(partialViewName: "_MovieCard", movie)*@
                </div>
            }
        </div>
    </div>
</div>

MovieShopMVC/Views/Home/GetHighestGrossingMovies.cshtml
@{
    ViewData["Title"] = "Get Highest Grossing Movies Page";
}

<h2>
    Highest Grossing Movie, get from db
</h2>

MovieShopMVC/Views/Home/Index.cshtml
@model List<ApplicationCore.Models.MovieCardResponseModel>

@{
    ViewData["Title"] = "Home Page";
}

<div class="rounded">
    <div class="container-fluid bg-light">
        <div class="row">
            @foreach (var movie in @Model)
            {
                <div class="col-3">
                    <partial name="_MovieCard" model="movie"/>
                    @*@await Html.PartialAsync(partialViewName: "_MovieCard", movie)*@ 
                </div>
            }
        </div>
    </div>
</div>

MovieShopMVC/Views/Shared/_GenresDropdown.cshtml
@using ApplicationCore.ServiceInterfaces@inject ApplicationCore.ServiceInterfaces.IGenreService genreService@foreach (var genre in await genreService.GetAllGenres()){    <a asp-controller="genres" asp-action="details" asp-route-id="@genre.Id" class="dropdown-item">@genre.Name</a>}

MovieShopMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieShopMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark text-white border-bottom box-shadow mb-3">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MovieShopMVC</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Genres
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @*@{ Html.RenderAction("Index", "Genres"); }*@
                            <partial name="_GenresDropdown" />
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
            <partial name="_LoginPartial" />
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieShopMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MovieShopMVC/Views/Shared/_MovieCard.cshtml
@model ApplicationCore.Models.MovieCardResponseModel


<div class="card mb-4 shadow bg-light">
    <a asp-controller="Movies" asp-action="Details" asp-route-id="@Model.Id">
        <img src="@Model.PosterUrl" style="width: 100%" alt="@Model.Title" />
    </a>
</div>

MovieShopMVC/Views/Users/TransactionComplete.cshtml
@model ApplicationCore.Models.MovieCardResponseModel
<h3 class="text-center">You have bought @Model.Title</h3>
<div class="container-fluid">
    <div class="row">
        <div class="col-4 offset-4">
            <partial name="_MovieCard" model="@Model" />
        </div>
    </div>
</div>